= Tests avec Internet Explorer 
:published_at: 2015-03-18
:hp-tags: NodeJS,Karma,JasmineJS,ModernIE,Windows

== Objectif

Nous avons actuellement une batterie de tests se lançant grâce à https://karma-runner.github.io[Karma] sur différents navigateurs.
Nous souhaiterions pouvoir valdier nos tests sur l'ensemble des versions d'Internet Explorer que nous supportons.

== Prérequis

Microfost fournit des machines virtuelles contenant différentes versions de systême d'exploitation avec leur version d'Internet Explorer associée.

Vous les trouverez sur ce site: https://www.modern.ie[ModernIE]
Pour automatiser la manipulation des vms,nous allons utiliser les outils suivant:

https://github.com/xdissent/ievms[IEVMS] pour l'installation des vms
https://github.com/xdissent/iectrl/[IECTRL] pour la gestion des vms
https://github.com/xdissent/karma-ievms[Karma-IEVMS] pour utiliser Karma et les ModernIE

L'ensemble des outils a été développé par https://github.com/xdissent[xdissent] pour des Unix like OS.


Il va falloir faire quelques manipulations pour les faire fonctionner sous Windows.Il faut avoir https://www.cygwin.com/[Cygwin] installé sur son poste et présent dans la %PATH% ainsi que VirtualBox.

== Installation

Il faut:

* télécharger le script Bash https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh[IEVMS] dans _D:\Vms\VirtualBox_ (ou tout autre répertoire).

* commenter les lignes 

[source,bash]
----
# Dans le 'main' à la fin du fichier

check_system

check_unar
----

[source,bash]
----
#Modifier la fonction check_md5
check_md5() {
    # local md5
    # case $kernel in
        # Darwin) md5=`md5 "${1}" | rev | cut -c-32 | rev` ;;
        # Linux) md5=`md5sum "${1}" | cut -c-32` ;;
    # esac
    # if [ "${md5}" != "${2}" ]
    # then
        # log "MD5 check failed for ${1} (wanted ${2}, got ${md5})"
        # return 1
    # fi
    log "MD5 check succeeded for "
}
----

* installer http://unarchiver.c3.cx/commandline[unar] pour Windows

il faut copier le contenu du zip dans _D:\Vms\VirtualBox_ et dans _cygwin\bin_

* créer le lanceur _launch.cmd_ dans _D:\Vms\VirtualBox_

[source,dos]
----
set IEVMS_VERSIONS=7 8 9 10
set INSTALL_PATH=D:\\Vms\\VirtualBox\\ievms
del /S/Q %INSTALL_PATH%\*.vmdk
bash ievms.sh
exit
----

* lancer _D:\Vms\VirtualBox\launch.cmd_

== Compatiblité Windows

Pour ajouter la compatiblité avec Windows, j'ai créé un https://github.com/malys/iectrl.git[fork] avec le https://github.com/xdissent/iectrl/pull/22[pull request] associé.

Il faut appliquer manuellement les correctifs sur ievms.js si le pull request n'a pas été intégré.
Cette modification impacte le project IECTRL et Karma-IEVMS.

[source,dos]
----
npm install -g iectrl

rem dans le project
npm install karma-ievms --save-dev
----

== Contrôle des vms

[source,dos]
----
iectrl --help

  Usage: iectrl [options] [command]

  Commands:
    clean [names] restore virtual machines to the clean snapshot
    close [names] close all running IE processes in virtual machines
    install [options] [names] install virtual machines with ievms
    nuke [names] remove all traces of virtual machines
    list         list available virtual machines
    open [options] [names] [url] open a URL in IE
    rearm [options] [names] rearm virtual machines
    reinstall [options] [names] reinstall virtual machines
    restart [options] [names] restart virtual machines
    screenshot [names] [output] save screenshots for virtual machines
    shrink [options] [names] shrink disk usage for virtual machines
    start [options] [names] start virtual machines
    status [options] [names] report the status of one or more vms
    stop [options] [names] stop virtual machines
    uninstall [options] [names] uninstall virtual machines
    uploaded [names] report the last time the VM was uploaded to modern.ie
  Options:
    -h, --help     output usage information
    -V, --version  output the version number
----

Vérifier le bon fonctionnement de votre installation.

[source,dos]
----

iectrl open -s 6,8 http://modern.ie

rem les vms doivent démarrer et le IE doit se lancer
----

== Lancement des tests

Dans le configuration de Karma; il faut ajouter:

[source,javascript]
----
browsers : [ 'IE6 - WinXP', 'IE7 - WinXP', 'IE8 - WinXP', 'IE9 - Win7', 'IE10 - Win7' ]
----

Les outils utilisent la librairie https://github.com/visionmedia/debug[debug].
Pour activer le mode _debug_, il faut déclarer:

[source,dos]
----
set -x DEBUG 'iectrl:*'
----


[source,dos]
----
...

IE 9.0.0 (Windows 7): Executed 236 of 236 SUCCESS (1.84 secs / 15 mins 14.946 secs)
IE 9.0.0 (Windows 7): Executed 236 of 236 SUCCESS (1.626 secs / 1.485 secs)
  iectrl:IE10 - Win7 waitForRunning +368ms
  iectrl:IE10 - Win7 _waitForStatus: RUNNING +1ms
...
----

== Planification

Une tâche planifiée va supprimer et recréer les vms.

[source,dos]
----
cmd /C uninstall.cmd
cmd /C launch.cmd
exit
----

[source,dos]
----
Rem uninstall.cmd
Rem Remove VMS
@ECHO OFF
SET LIST="IE8 - WinXP","IE9 - Win7","IE10 - Win7"

SET LIST=ECHO %LIST:,=^^^&ECHO %

FOR /F "delims=" %%i IN ('%LIST%') DO (
	echo iectrl stop %%i
	cmd /C "iectrl stop %%i"
	echo iectrl uninstall %%i
	cmd /C "iectrl uninstall %%i"
)
exit
----


== Ressources

https://www.modern.ie[ModernIE]
https://github.com/xdissent/ievms[IEVMS]
https://github.com/xdissent/iectrl/[IECTRL] 
https://github.com/xdissent/karma-ievms[Karma-IEVMS] 