= Javascript Killers
:published_at: 2016-02-15
:hp-tags: build,Javascript,tools


== Liste des langages

[options="header,footer"]
|=======================
|Nom |Site      
|TypeScript    |https://www.typescriptlang.org/   
|CoffeeScript   |http://coffeescript.org/     
|Rust    |https://www.rust-lang.org/en-US/ 
|Dart      |https://www.dartlang.org/
|ES6  http://es6-features.org/
|=======================

== Tendances 

++++
<script type="text/javascript">
window.listMVC=[
	{name:'TypeScript',url:'https://www.typescriptlang.org/   ',keywords:['typescript','typescript','typescript','typescript']},
	{name:'CoffeeScript',url:'http://coffeescript.org/',keywords:['coffeescript','coffeescript','coffeescript','coffeescript']},
    {name:'Rust',url:'https://www.rust-lang.org/en-US/ ',keywords:['rust','rust','rust','rust']},
    {name:'Dart',url:'https://www.dartlang.org/',keywords:['dart','dart','dart','dart']},
    {name:'ES6',url:'http://es6-features.org/',keywords:['es6','es6','es6','es6']}
    ];

</script>
++++

=== Stackoverflow

++++

<a id='stofh' href="" target="_blank">
Stackoverflow Trends
</a>
<p>

<script type="text/javascript">
var a =  document.getElementById('stofh')
a.href = 'http://sotagtrends.com/?tags=['+ window.listMVC.map(function(it) {
  return it.keywords[0];
}).join(',') +  ']';

</script>
++++



=== Reddit

++++

<a id='redh0' href="" target="_blank">_</a>
<br>
<a id='redh1' href="" target="_blank">_</a>
<br>
<a id='redh2' href="" target="_blank">_</a>
<br>
<a id='redh3' href="" target="_blank">_</a>
<br>
<a id='redh4' href="" target="_blank">_</a>

<script type="text/javascript">
for(i=0;i<5;i++){
  var a =  document.getElementById('redh'+ i)
  a.href="https://www.reddit.com/r/"+window.listMVC[i].keywords[1]+ "/about/traffic";
  a.innerHTML = 'Reddit for ' + window.listMVC[i].name
}
</script>
++++



=== Google

++++

<a id='goo1' href="" target="_blank">Google trends</a>

<script type="text/javascript">
  var a =  document.getElementById('goo1')
  a.href ='https://www.google.com/trends/explore#cat=0-5&q=';
  a.href += encodeURIComponent(window.listMVC.map(function(it) {
  return it.keywords[2];
}).join(', '));
  a.href +='&date=today%2012-m&cmpt=q&tz=Etc%2FGMT-2';

</script>
++++

=== GitHub/NPM

++++
<a id='npm' href="" target="_blank">NPM trends</a>

<script type="text/javascript">
  var a =  document.getElementById('npm')
  a.href ='http://www.npmtrends.com/';
  a.href += window.listMVC.map(function(it) {
  return it.keywords[3];
}).join('-vs-');
</script>
++++



=== Articles
